# Generated by Django 4.2.10 on 2024-02-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cryptoapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowerFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepal_length', models.FloatField(default=6.1)),
                ('sepal_width', models.FloatField(default=2.8)),
                ('petal_length', models.FloatField(default=4.7)),
                ('petal_width', models.FloatField(default=1.2)),
            ],
        ),
    ]
